"""The Pondsworth tutorial data, shipped inside the package so `duck-soup tutorial` works for
pipx/pip/Docker installs, not just a clone of the repository.

The files live in `duck_soup/tutorial/` (generated by scripts/build_tutorial.py). `install()`
copies them into a project folder laid out the way the docs and the editor expect:

    <folder>/data/tutorial/*.geojson, categories.csv   the sample data
    <folder>/pipelines/pondsworth.yaml                every tutorial example, one pipeline each

The config's source paths are relative (`data/tutorial/...`), so it runs from `<folder>`, and
`pipelines/` is where the editor's load dropdown looks when `<folder>` is its project folder.
"""
from __future__ import annotations

import shutil
from importlib import resources
from pathlib import Path

CONFIG_NAME = "pondsworth.yaml"
DATA_DIR = Path("data") / "tutorial"
PIPELINES_DIR = Path("pipelines")


def _bundled():
    return resources.files("duck_soup") / "tutorial"


def plan(dest: Path) -> list[tuple[object, Path]]:
    """(bundled file, target path) for every file install() would write."""
    out = []
    for item in sorted(_bundled().iterdir(), key=lambda p: p.name):
        if not item.is_file():
            continue
        sub = PIPELINES_DIR if item.name == CONFIG_NAME else DATA_DIR
        out.append((item, dest / sub / item.name))
    return out


def install(dest: str | Path = ".", force: bool = False) -> list[Path]:
    """Copy the tutorial data and config into `dest`; returns the paths written.

    Refuses (FileExistsError, naming the files) to overwrite anything unless `force` is set,
    so re-running it can't clobber a config someone has been editing.
    """
    dest = Path(dest)
    files = plan(dest)
    existing = [target for _, target in files if target.exists()]
    if existing and not force:
        names = ", ".join(str(p) for p in existing)
        raise FileExistsError(f"already exists: {names} (use --force to overwrite)")
    written = []
    for item, target in files:
        target.parent.mkdir(parents=True, exist_ok=True)
        with resources.as_file(item) as src:
            shutil.copyfile(src, target)
        written.append(target)
    return written
